name: Publish to npm

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: bun install
      
      - name: Build
        run: bun run build && bun run build:types
      
      - name: Set version from GitHub release
        run: |
          RELEASE_VERSION=${GITHUB_REF#refs/tags/}
          RELEASE_VERSION=${RELEASE_VERSION#v}
          echo "Setting version to $RELEASE_VERSION"
          # Use npm version with --allow-same-version to ensure it works even if the version is already set
          bun x npm version $RELEASE_VERSION --allow-same-version --no-git-tag-version
      
      - name: Publish to npm
        run: bun x npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 